import fs from "node:fs";
import type { KarabinerRules, Manipulator, To } from "./types";

type Shortcut = {
	group: string;
	keys: string[];
	action: string;
};

type Config = {
	profiles: Array<{
		complex_modifications: { rules: KarabinerRules[] };
	}>;
};

const config = JSON.parse(fs.readFileSync("karabiner.json", "utf8")) as Config;
const rules = config.profiles[0].complex_modifications.rules;

const groupNames: Record<string, string> = {
	o: "Open apps",
	x: "Quit apps",
	w: "Window",
	s: "System",
	r: "Raycast",
};

const keyNames: Record<string, string> = {
	caps_lock: "Caps Lock",
	right_command: "Right Command",
	semicolon: ";",
	delete_or_backspace: "Backspace",
	left_arrow: "Left arrow",
	right_arrow: "Right arrow",
	up_arrow: "Up arrow",
	down_arrow: "Down arrow",
	display_brightness_increment: "Increase display brightness",
	display_brightness_decrement: "Decrease display brightness",
	volume_increment: "Volume up",
	volume_decrement: "Volume down",
	play_or_pause: "Play or pause",
	fastforward: "Next media track",
};

const label = (key: string) => {
	const name =
		keyNames[key] ??
		(key.length === 1 ? key.toUpperCase() : key.replaceAll("_", " "));
	return name.charAt(0).toUpperCase() + name.slice(1);
};

function sublayer(manipulator: Manipulator) {
	const condition = manipulator.conditions?.find(
		(item) =>
			"name" in item &&
			typeof item.name === "string" &&
			item.name.startsWith("hyper_sublayer_") &&
			item.value === 1,
	);
	return condition && "name" in condition
		? condition.name.replace("hyper_sublayer_", "")
		: undefined;
}

function describeTo(to: To[] = []) {
	const target = to[0];
	if (!target) return "Run command";
	if ("key_code" in target) return label(target.key_code);
	if ("shell_command" in target) {
		const command = target.shell_command;
		const app = command.match(/open -a '(.+)\.app'/)?.[1];
		if (app) return `Open ${app}`;
		const url = command.match(/(?:open(?: -g)? )(.+)/)?.[1];
		if (url) {
			const slug = url.split("/").filter(Boolean).at(-1) ?? url;
			return slug
				.replaceAll("-", " ")
				.replace(/\b\w/g, (letter) => letter.toUpperCase());
		}
		return command;
	}
	return "Run command";
}

function cleanDescription(description: string | undefined, to: To[]) {
	if (!description || description === "hjkl to arrow keys") return describeTo(to);
	if (description.startsWith("Open -a '"))
		return description.replace(/^Open -a '/, "Open ").replace(/\.app'$/, "");
	if (description.startsWith("Open raycast:")) return describeTo(to);
	if (description.startsWith("Window: "))
		return description
			.replace("Window: ", "")
			.replaceAll("-", " ")
			.replace(/\b\w/g, (letter) => letter.toUpperCase());
	return description
		.replace("right cmd -> backspace on click", "Backspace")
		.replace(/\b\w/g, (letter) => letter.toUpperCase());
}

const shortcuts: Shortcut[] = [];

for (const rule of rules) {
	for (const manipulator of rule.manipulators) {
		if (!manipulator.from?.key_code) continue;
		if (
			manipulator.to?.some((item) => "set_variable" in item) &&
			!manipulator.to_if_alone
		)
			continue;

		const layer = sublayer(manipulator);
		const mandatory = manipulator.from.modifiers?.mandatory ?? [];
		const usesHyper = manipulator.conditions?.some(
			(item) => "name" in item && item.name === "hyper" && item.value === 1,
		);
		const chord = layer
			? ["Hyper", label(layer), label(manipulator.from.key_code)]
			: mandatory.length
				? [...mandatory.map(label), label(manipulator.from.key_code)]
				: usesHyper
					? ["Hyper", label(manipulator.from.key_code)]
					: [label(manipulator.from.key_code)];
		const keys = manipulator.to_if_alone ? [...chord, "tap"] : chord;
		const group = layer
			? groupNames[layer] ?? `Hyper + ${label(layer)}`
			: mandatory.includes("right_command")
				? "Navigation"
				: "Basics";

		shortcuts.push({
			group,
			keys,
			action: manipulator.to_if_alone
				? describeTo(manipulator.to_if_alone)
				: cleanDescription(manipulator.description, manipulator.to ?? []),
		});
	}
}

const order = [...new Set(shortcuts.map(({ group }) => group))];
const output = `// Generated by generate-shortcuts.ts. Do not edit.\nwindow.SHORTCUT_INDEX = ${JSON.stringify({ order, shortcuts }, null, 2)};\n`;
fs.writeFileSync("shortcuts-data.js", output);
console.log(`Generated shortcuts-data.js (${shortcuts.length} shortcuts)`);
