// Generated by generate-shortcuts.ts. Do not edit.
window.SHORTCUT_INDEX = {
  "order": [
    "Navigation",
    "Basics",
    "Open apps",
    "Quit apps",
    "Window",
    "System",
    "Raycast"
  ],
  "shortcuts": [
    {
      "group": "Navigation",
      "keys": [
        "Right Command",
        "H"
      ],
      "action": "Left arrow"
    },
    {
      "group": "Navigation",
      "keys": [
        "Right Command",
        "J"
      ],
      "action": "Down arrow"
    },
    {
      "group": "Navigation",
      "keys": [
        "Right Command",
        "K"
      ],
      "action": "Up arrow"
    },
    {
      "group": "Navigation",
      "keys": [
        "Right Command",
        "L"
      ],
      "action": "Right arrow"
    },
    {
      "group": "Navigation",
      "keys": [
        "Right Command",
        ";"
      ],
      "action": "Backspace"
    },
    {
      "group": "Basics",
      "keys": [
        "Right Command",
        "tap"
      ],
      "action": "Backspace"
    },
    {
      "group": "Basics",
      "keys": [
        "Caps Lock",
        "tap"
      ],
      "action": "Escape"
    },
    {
      "group": "Basics",
      "keys": [
        "Hyper",
        "H"
      ],
      "action": "Left arrow"
    },
    {
      "group": "Basics",
      "keys": [
        "Hyper",
        "J"
      ],
      "action": "Down arrow"
    },
    {
      "group": "Basics",
      "keys": [
        "Hyper",
        "K"
      ],
      "action": "Up arrow"
    },
    {
      "group": "Basics",
      "keys": [
        "Hyper",
        "L"
      ],
      "action": "Right arrow"
    },
    {
      "group": "Basics",
      "keys": [
        "Hyper",
        ";"
      ],
      "action": "Backspace"
    },
    {
      "group": "Basics",
      "keys": [
        "Hyper",
        "F7"
      ],
      "action": "Toggle Caps Lock"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "1"
      ],
      "action": "Open 1Password"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "2"
      ],
      "action": "Open Helium"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "3"
      ],
      "action": "Open T3 Code"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "B"
      ],
      "action": "Open Obsidian"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "E"
      ],
      "action": "Open Spark Desktop"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "F"
      ],
      "action": "Open Finder"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "G"
      ],
      "action": "Open Ghostty"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "H"
      ],
      "action": "Open Things"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "M"
      ],
      "action": "Open Spotify"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "S"
      ],
      "action": "Open Slack"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "T"
      ],
      "action": "Open Telegram"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "V"
      ],
      "action": "Open Cursor"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "W"
      ],
      "action": "Open Google Chrome"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "Z"
      ],
      "action": "Open Zed"
    },
    {
      "group": "Open apps",
      "keys": [
        "Hyper",
        "O",
        "U"
      ],
      "action": "Open Figma"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "1"
      ],
      "action": "Quit 1Password"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "2"
      ],
      "action": "Quit Helium"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "3"
      ],
      "action": "Quit T3 Code"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "B"
      ],
      "action": "Quit Obsidian"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "E"
      ],
      "action": "Quit Spark Desktop"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "F"
      ],
      "action": "Quit Finder"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "G"
      ],
      "action": "Quit Ghostty"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "H"
      ],
      "action": "Quit Things"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "M"
      ],
      "action": "Quit Spotify"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "S"
      ],
      "action": "Quit Slack"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "T"
      ],
      "action": "Quit Telegram"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "V"
      ],
      "action": "Quit Cursor"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "W"
      ],
      "action": "Quit Google Chrome"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "Z"
      ],
      "action": "Quit Zed"
    },
    {
      "group": "Quit apps",
      "keys": [
        "Hyper",
        "X",
        "U"
      ],
      "action": "Quit Figma"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        ";"
      ],
      "action": "Hide"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "Y"
      ],
      "action": "Previous Display"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "O"
      ],
      "action": "Next Display"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "K"
      ],
      "action": "Top Half"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "J"
      ],
      "action": "Bottom Half"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "H"
      ],
      "action": "Left Half"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "L"
      ],
      "action": "Right Half"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "F"
      ],
      "action": "Maximize"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "U"
      ],
      "action": "Previous Tab"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "I"
      ],
      "action": "Next Tab"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "N"
      ],
      "action": "Next Window"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "B"
      ],
      "action": "Back"
    },
    {
      "group": "Window",
      "keys": [
        "Hyper",
        "W",
        "M"
      ],
      "action": "Forward"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        "U"
      ],
      "action": "Volume up"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        "J"
      ],
      "action": "Volume down"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        "I"
      ],
      "action": "Increase display brightness"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        "K"
      ],
      "action": "Decrease display brightness"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        "L"
      ],
      "action": "Q"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        "P"
      ],
      "action": "Play or pause"
    },
    {
      "group": "System",
      "keys": [
        "Hyper",
        "S",
        ";"
      ],
      "action": "Next media track"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "1"
      ],
      "action": "Connect Favorite Device 1"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "2"
      ],
      "action": "Connect Favorite Device 2"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "C"
      ],
      "action": "Pick Color"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "N"
      ],
      "action": "Dismiss Notifications"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "L"
      ],
      "action": "Create Mxs Is Shortlink"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "E"
      ],
      "action": "Search Emoji Symbols"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "P"
      ],
      "action": "Confetti"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "A"
      ],
      "action": "Ai Chat"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "S"
      ],
      "action": "Index"
    },
    {
      "group": "Raycast",
      "keys": [
        "Hyper",
        "R",
        "H"
      ],
      "action": "Clipboard History"
    }
  ]
};
